#!/usr/bin/env bash
set -euo pipefail
source_path=${BASH_SOURCE[0]}
while [ -L "$source_path" ]; do
  base=$(cd -P "$(dirname "$source_path")" && pwd)
  source_path=$(readlink "$source_path")
  [[ $source_path = /* ]] || source_path=$base/$source_path
done
runtime=$(cd -P "$(dirname "$source_path")/../.." && pwd)
exec just --justfile "$runtime/justfile" run "$@"
